### ISSUE TITLE
RBAC issue with 0.7.1 installer in Kube 1.8.5

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/project#97]
From `mthird` in Slack:

the log shows "Ensuring CustomResourceDefinition..."

F1218 21:10:03.790083       1 controller.go:216] customresourcedefinitions.apiex
tensions.k8s.io "postgreses.kubedb.com" is forbidden: User "system:serviceaccoun
t:default:kubedb-operator" cannot get customresourcedefinitions.apiextensions.k8
s.io at the cluster scope

**Comment by mthird** [comment]
`
michaelthird@mthirdp51:~$ kubectl describe -n kube-system serviceaccount kubedb-operator
Name:         kubedb-operator
Namespace:    kube-system
Labels:       app=kubedb
Annotations:  <none>

Image pull secrets:  <none>

Mountable secrets:   kubedb-operator-token-z4dnp

Tokens:              kubedb-operator-token-z4dnp

Events:  <none>
`

**Comment by mthird** [comment]
```
~$ kubectl describe -n kube-system clusterrole kubedb-operator
Name:         kubedb-operator
Labels:       app=kubedb
Annotations:  <none>
PolicyRule:
  Resources                               Non-Resource URLs  Resource Names  Verbs
  ---------                               -----------------  --------------  -----
  *.kubedb.com                            []                 []              [*]
  customresourcedefinitions.extensions    []                 []              [get create delete]
  endpoints                               []                 []              [get]
  events                                  []                 []              [create]
  jobs.batch                              []                 []              [get create delete]
  persistentvolumeclaims                  []                 []              [list delete]
  pods                                    []                 []              [get create list delete deletecollec
tion]
  rolebindings.rbac.authorization.k8s.io  []                 []              [get create update delete]
  roles.rbac.authorization.k8s.io         []                 []              [get create update delete]
  secrets                                 []                 []              [get create delete]
  serviceaccounts                         []                 []              [get create delete]
  servicemonitors.monitoring.coreos.com   []                 []              [get create update]
  services                                []                 []              [get create delete]
  statefulsets.apps                       []                 []              [get create update delete]
  storageclasses.storage.k8s.io           []                 []              [get]
  thirdpartyresources.extensions          []                 []              [get create delete]
```

**Comment by mthird** [comment]
```
~$ kubectl describe -n kube-system clusterrolebinding kubedb-operator
Name:         kubedb-operator
Labels:       app=kubedb
Annotations:  <none>
Role:
  Kind:  ClusterRole
  Name:  kubedb-operator
Subjects:
  Kind            Name             Namespace
  ----            ----             ---------
  ServiceAccount  kubedb-operator  kube-system
```

**Comment by mthird** [comment]
```
~$ kubectl describe -n kube-system deployment kubedb-operator
Name:                   kubedb-operator
Namespace:              kube-system
CreationTimestamp:      Mon, 18 Dec 2017 16:37:32 -0500
Labels:                 app=kubedb
Annotations:            deployment.kubernetes.io/revision=1
Selector:               app=kubedb
Replicas:               1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:           app=kubedb
  Service Account:  kubedb-operator
  Containers:
   operator:
    Image:  kubedb/operator:0.7.1
    Port:   8080/TCP
    Args:
      run
      --address=:8080
      --rbac=true
      --v=3
    Environment:
      OPERATOR_NAMESPACE:   (v1:metadata.namespace)
    Mounts:                <none>
  Volumes:                 <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   kubedb-operator-5fdd67fb7 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  3m    deployment-controller  Scaled up replica set kubedb-operator-5fdd67fb7 to 1
```

**Comment by tamalsaha** [comment]
Fixed in 0.8.0-x release

**Comment by ChrisTerBeke** [comment]
I'm using 0.8.0-beta.2 targeting k8s 1.9.7 and I'm still having this issue.

**Comment by apobbati** [comment]
Still having this issue in `0.12.0`
